### ISSUE TITLE
I don't like it, personally

### ISSUE THREAD

**Issue by Vhou-Atroph** [BoggoTV/boggo.tv#1]
Fix it please

**Comment by BoggoTV** [comment]
I like it personally. Respectfully, i think you should go away and sit in a small hole for several hours in such a way of which I will not be aware of your presence on this planet at any given moment of my life. Please consider this, and close your issue if there are no more questions. Thank you.

**Comment by BoggoTV** [comment]
you are an issue

**Comment by Vhou-Atroph** [comment]
I am sorry for my rude comments. I have changed and grown as a person. :)
